server:
  port: 8080


spring:
  application:
    name: Cloud-GateWay
  cloud:
    #nacos 注册中心
    nacos:
      discovery:
        server-addr: 192.168.22.222:18848
    #路由配置
    gateway:
      routes:
        - id: Cloud-Work
          uri: lb://Cloud-Work-Test
          predicates:
            - Path=/getuser/**


