server:
  port: 8090
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders: #此处配置绑定的rabbitmq的信息
        defaultRabbit: # 表示定义的名称 用于binding 整合
          type: rabbit #消息组件的类型
      bindings: # 服务整合处理
        input: # 这个名字是一个通道名称
          destination: studyExchange # 表示要用Exchange 名称
          content-type: application/json # 设置消息类型
          binder: defaultRabbit
    nacos:
      discovery:
        server-addr: 192.168.22.222:18848
  application:
    name: Cloud-SpringCloudStream-Study-Consumer










#  datasource:
#    url: jdbc:postgresql://192.168.22.222:16789/powerdev20220212?useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: power
#    password: riest9510
#    driver-class-name: org.postgresql.Driver
#  redis:
#    host: 192.168.22.222
#    password:
#    port: 36379
#    database: 2
