spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.222:18848
      config:
        server-addr: 192.168.22.222:18848


dubbo:
  scan:
    base-packages: riest.springplatform.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.22.222:18848
server:
  port: 8888

